FeriaCultiva/FeriaCultiva/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #URL Principal
    path('', views.Inicio, name="start"),

    path('administrador/', views.Administrador),

    path('agregarFeriante', include('apps.feriante.urls')),

    #LOGIN and LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    path('eventos/', include('apps.evento.urls')),

]

FeriaCultiva/apps/feriante/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "feriante"

urlpatterns = [

    #URL Principal
    path('', views.AgregarFeriante.as_view(), name="agregar"),

]

FeriaCultiva/templates/administrador.html
<!DOCTYPE html>
<html lang="es">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0, shrink-to-fit=no">

    <!-- Estilo css-->


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" comrossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <!-- FONTAWSOME -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
     
    <!-- Fuente google font-->
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- falta el logo-->
    <link rel="icon" href="images/logochico.png" type="image/x-icon">
    <title>Feria Cultiva</title>
    <style type="text/css">
    	

    </style>
  </head>
  <body>

  		<nav>
        <div class="container-fluid" style="background-color: #a9c52f;">
          <div class="navbar-bran">
            <div class="">
            <a class="" href="#">

                <img id="logo"  width="230" height="100"  class="d-inline-block mx-auto" alt="Feria Cultiva" style="padding-left: 100px;">
            </a>

           <div class="d-inline-block">
              
                     <h1 style="color: #fff; font-weight: bold; font-size: 30px;font-family: 'Roboto Slab', serif;" >BIENVENIDO AL PANEL DE ADMINISTRACIÓN DE FERIA CULTIVA </h1>
            </div>

           
           </div>
            
          </div>
        </div>
     </nav>



<div class="container-fluid">

  <div class="row">

      <div class="jumbotron mx-auto" style=" font-family: 'Roboto Slab', serif; background-color:#fFF; margin-top:50px;">
            
      
            <hr class="my-4">  
            

        <div>
            

          
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-4" >
            <div class="card shadow" style="width: 20rem;height: 300px;background-color: #a9c52f; margin-bottom: 20px;">
              <img class="card-image-top" src="images/feriantes.png">
                <div class="card-body text-center">
                  
                  <p style="color: #fff;  font-family: 'Roboto Slab', serif; font-weight: bold;">
                   FERIANTES
                  </p>
                   <a href="{% url 'feriante:agregar' %}" class="btn " style="background-color: #2c5d63; color: #fff;">Agregar</a>
                </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card shadow" style="width: 20rem;height: 300px; background-color: #a9c52f;
            margin-bottom: 20px;">
              <img class="card-image-top" src="images/ambiente.png">
                <div class="card-body text-center">
               <p style="color: #fff;  font-family: 'Roboto Slab', serif; font-weight: bold;">
                  AMBIENTE Y SALUD
                  </p>
                  
                    <a href="#" class="btn " style="background-color: #2c5d63; color: #fff;">Actualizar</a>
                </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="card shadow" style="width: 20rem; height: 300px;background-color: #a9c52f;
            margin-bottom: 20px;">
              <img class="card-image-top" src="images/fechas.png">
                <div class="card-body text-center">
                 <p style="color: #fff;  font-family: 'Roboto Slab', serif; font-weight: bold;">PRÓXIMAS FECHAS</p>
                
                    <a href="#" class="btn " style="background-color: #2c5d63; color: #fff;">Actualizar</a>
                </div>
            </div>
          </div>
        </div>
      </div>
           

      </div>
  </div>

</div>




  <body>

FeriaCultiva/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
	
	<title>Iniciar Sesión</title>
</head>
<body class="principal" style="background-image: url({% static 'img/back.png' %}); ">
	<div class="container-fluid" >
		
		<div class="row">

			
			<div class="mx-auto" height="667" style="font-family: 'Roboto Slab', serif;">
				<div class="row d-flex justify-content-center align-items-center">
					<div class="card shadow-lg p-3 mb-5 rounded" style="margin-top: 12%; background-color: #a9c52f;">
						<div class="card-header d-flex justify-content-center " style="background-color: #a9c52f; ">
							<img clas="card-img-top" src="{% static 'img/inicio-sesion.png' %}" alt="">	
						
						</div>
							<h3 style="text-align: center; color: white; font-weight: bold">BIENVENIDO</h3>
						<div class="card-body">
							{% if form.errors %}
								<div class="alert" style="background-color: red;"> {{form.errors}} </div>
							{% endif %}
							<form action="{% url 'login' %}" method="POST">{% csrf_token %}
								<div class="form-group">
								    <label for="exampleInputEmail1">Nombre de Usuario o Correo electrónico</label>
								    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Ingrese usuario">
								    <small id="emailHelp" class="form-text text-muted">No compartiremos tu direccion de correo con nadie más.</small>
								  </div>
								  <div class="form-group">
								    <label for="exampleInputPassword1">Contraseña</label>
								    <input type="password" class="form-control" name="password" placeholder="Contraseña">
								    <small id="emailHelp" class="form-text text-muted">Olvidaste tu contraseña?
								    	<a href="" style="color: white; text-decoration: underline;">Restaurar</a></small>
								  </div>

								  
								  <input type="hidden" name="next" value="{{ next }}" />
								  <div class="" style="text-align: center;">
								  <button  type="submit" class="btn btn-primary" style="background-color: #2c5d63;">Ingresar</button>
								  </div>
							</form>
						</div>				
					</div>
				</div>				
			</div>

		</div>

	</div>


</body>
</html>

FeriaCultiva/templates/start.html
{% extends 'base.html' %}
{% load static %}

	{% block contenido %}
	
<!-- Full Page Image Header with Vertically Centered Content -->
      <!-- Full Page Image Header with Vertically Centered Content -->
<div>
<header>


  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
     
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: url({% static 'img/slide11.png' %})">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">First Slide</h2>
          <p class="lead">This is a description for the first slide.</p>
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('{% static 'img/slide12.png' %}')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Second Slide</h2>
          <p class="lead">This is a description for the second slide.</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('{% static 'img/slide9.png' %}')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Third Slide</h2>
          <p class="lead">This is a description for the third slide.</p>
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('{% static 'img/slide6.png' %}')">
        <div class="carousel-caption d-none d-md-block">
          <h2 class="display-4">Third Slide</h2>
          <p class="lead">This is a description for the third slide.</p>
        </div>
      </div>
      
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>
</header>

<!-- Page Content -->
<section class="py-1" style="background-image: url({% static 'img/back.png' %})" >
  <div class="container">
    <h2 class="font-weight-light">Page Content</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.</p>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.



    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.



    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.



    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.




    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.



    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita. </p>
  </div>
</section>


	<div class="col-4 nav">
		<div style="margin: 10px" class="d-flex align-items-center">
		{% if user.is_authenticated %}
			<b class="text-light mr-2">Hola, {{user.username}}!</b>
			<a href="{% url 'logout' %}">Logout</a>
		{% else %}
			<a href="{% url 'login' %}">Login</a>
		{% endif %}
	</div>	
  </div>
	{% endblock contenido %}